# baseurl = "https://knowckx.github.io"
# # baseurl = "https://knowckx.github.io"

baseurl="/"

languageCode = "zh-cn"
title = "Knowckx's Blog"

# GA Tracking ID
googleAnalytics = "G-4DX39HKR9W"

# 指定时区 因为 hugo 默认时区比中国时间慢 8 小时
timezone = "Asia/Shanghai"


# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 7

enableGitInfo = true
[frontmatter]
  lastmod = ['lastmod', 'modified', ':git', ':fileModTime', 'date'] # 按顺序依次获取


# [sitemap]
#   changefreq = 'weekly'
#   filename = 'sitemap.xml'
#   priority = 0.5

# enableRobotsTXT = true