# Change baseurl before deploy
# baseurl = "https://knowckx.github.io"
baseurl = "https://knowckx.zone.id/"

languageCode = "en-us"
title = "Knowckx's Blog"

# GA Tracking ID
googleAnalytics = "G-4DX39HKR9W"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 7





