# Rename this file to languages.toml to enable multilingual support
[cn]
languageName = "Chinees"
languagedirection = "ltr"
title = "你好"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1