# Rename this file to languages.toml to enable multilingual support

[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "Knowckx's Blog"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Knowckx's Blog"
weight = 2


