# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true


# 很重要 可以帮助其他地址的静态blog 为.top域名贡献外链
[[social]]
identifier = "Blog"
name = "Blog"
url = "https://blog.knowckx.top/"


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/knowckx"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Email"
name = "Email"
url = "mailto:knowckx@foxmail.com"

[social.params]
icon = "mail"



# [social.params]
# icon = "brand-twitter"
